# Generated by Django 3.2.25 on 2024-12-18 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto_estacionamento', '0002_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tipo_usuario',
            field=models.CharField(choices=[('Comum', 'Comum'), ('VIP', 'VIP')], default='Comum', max_length=5),
        ),
    ]
