# Generated by Django 3.2.25 on 2024-12-19 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto_estacionamento', '0004_vaga'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='vaga',
            name='data_entrada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
