# Generated by Django 3.2.25 on 2024-12-20 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projeto_estacionamento', '0007_auto_20241219_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaga',
            name='data_entrada',
        ),
    ]
