# Generated by Django 3.2.25 on 2024-12-20 00:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projeto_estacionamento', '0008_remove_vaga_data_entrada'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoDeUso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('acao', models.CharField(choices=[('Entrada', 'Entrada'), ('Saída', 'Saída')], max_length=10)),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto_estacionamento.cliente')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto_estacionamento.vaga')),
            ],
        ),
    ]
