# Generated by Django 3.2.25 on 2024-12-20 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projeto_estacionamento', '0009_historicodeuso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicodeuso',
            name='data_hora',
        ),
    ]
