# Generated by Django 3.2.25 on 2024-12-20 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projeto_estacionamento', '0010_remove_historicodeuso_data_hora'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='tipo_usuario',
            new_name='tipo',
        ),
    ]
